In [1]:
import graphlab as gl


In [2]:
import numpy as np
sales=gl.SFrame('kc_house_data.gl')

This non-commercial license of GraphLab Create for academic use is assigned to vpsingh12157@gmail.com and will expire on June 28, 2019.


[INFO] graphlab.cython.cy_server: GraphLab Create v2.1 started. Logging: C:\Users\HP\AppData\Local\Temp\graphlab_server_1532266641.log.0


In [3]:
def numpy_data(sales , input_features ,output):
    sales['constant']=1
    input_features=['constant']+input_features
    features_sales=sales.select_columns(input_features)
    feature_matrix=features_sales.to_numpy()
    target_sarray=sales[output]
    target_numarray=target_sarray.to_numpy()
    
    return(feature_matrix , target_numarray)



In [4]:
def predict_output(feature_matrix , weights):
    prediction=np.dot(feature_matrix,weights)
    
    return(prediction)

In [5]:
def feature_derivative(errors, feature):
    
    derivative=np.dot(errors,feature)
    derivative=2*derivative
    
    return(derivative)

(example_features, example_output) = numpy_data(sales, ['sqft_living'], 'price') 
my_weights = np.array([0., 0.])
test_predictions = predict_output(example_features, my_weights) 
errors=test_predictions-example_output
feature=example_features[:,0]
derivate=feature_derivative(errors, feature)
print -np.sum(example_output)*2
derivate

-23345850022.0


-23345850022.0

In [6]:
from math import sqrt
def regression_gradient_descent(feature_matrix, output, initial_weights, step_size, tolerance):
    
    converged=False
    weights=np.array(initial_weights)
 
   
    while not converged:
        prediction=predict_output(feature_matrix , weights)
        errors=prediction-output
        
        gradient_sum_squares = 0
        
        for i in range(len(weights)):
            feature_col=feature_matrix[:,i]
            derivate=feature_derivative(errors ,feature_col)
            gradient_sum_squares+=(derivate*derivate)
            weights[i]-=step_size*derivate
            
        gradient_magnitude=sqrt(gradient_sum_squares)
        print " gradient magnitude :"
        print gradient_magnitude
        if gradient_magnitude<tolerance:
            converged=True
        
        
    return(weights)
        
    

In [7]:
train_data,test_data = sales.random_split(.8,seed=0)


In [8]:
simple_features = ['sqft_living']
my_output = 'price'
(simple_feature_matrix, output) = numpy_data(train_data, simple_features, my_output)
initial_weights = np.array([-47000., 1.])
step_size = 7e-12
tolerance = 2.5e7
simple_feature_matrix ,output

(array([[1.00e+00, 1.18e+03],
        [1.00e+00, 2.57e+03],
        [1.00e+00, 7.70e+02],
        ...,
        [1.00e+00, 1.53e+03],
        [1.00e+00, 1.60e+03],
        [1.00e+00, 1.02e+03]]),
 array([221900., 538000., 180000., ..., 360000., 400000., 325000.]))

In [9]:
simple_weight=regression_gradient_descent(simple_feature_matrix,output,[-47000., 1.],step_size,tolerance)


 gradient magnitude :
5.05515307744e+13
 gradient magnitude :
1.31274510235e+13
 gradient magnitude :
3.40899608253e+12
 gradient magnitude :
8.852635801e+11
 gradient magnitude :
2.2988926572e+11
 gradient magnitude :
59698688259.7
 gradient magnitude :
15502826422.1
 gradient magnitude :
4025844401.5
 gradient magnitude :
1045449748.16
 gradient magnitude :
271487891.86
 gradient magnitude :
70504114.6976
 gradient magnitude :
18320016.751


In [10]:
simple_weight


array([-46999.88716555,    281.91211912])

In [19]:
(test_simple_feature_matrix, test_output) =numpy_data(test_data, simple_features, my_output)

In [20]:
test_prediction=np.dot(test_simple_feature_matrix,simple_weight)

In [21]:
test_prediction

array([356134.44317093, 784640.86422788, 435069.83652353, ...,
       663418.65300782, 604217.10799338, 240550.4743332 ])

In [14]:
rss=test_prediction-test_output
rss=rss*2
np.sum(rss)

-32608763.35241878

In [28]:
model_features = ['sqft_living', 'sqft_living15']
output = 'price'
(final_features_matrix ,final_output)=numpy_data(train_data,model_features ,output)
initial_weights = np.array([-100000., 1., 1.])
step_size = 4e-12
tolerance = 1e9

In [29]:
final_weights=regression_gradient_descent(final_features_matrix,final_output,initial_weights,step_size,tolerance)

 gradient magnitude :
7.30720205489e+13
 gradient magnitude :
2.26732209651e+13
 gradient magnitude :
7.0607945821e+12
 gradient magnitude :
2.27568239427e+12
 gradient magnitude :
9.28984105638e+11
 gradient magnitude :
6.56307425178e+11
 gradient magnitude :
6.10615351821e+11
 gradient magnitude :
5.93078765307e+11
 gradient magnitude :
5.78705920128e+11
 gradient magnitude :
5.64945676163e+11
 gradient magnitude :
5.51538681425e+11
 gradient magnitude :
5.38452422879e+11
 gradient magnitude :
5.25676912708e+11
 gradient magnitude :
5.1320454369e+11
 gradient magnitude :
5.01028100319e+11
 gradient magnitude :
4.89140559101e+11
 gradient magnitude :
4.77535065233e+11
 gradient magnitude :
4.66204926754e+11
 gradient magnitude :
4.55143610499e+11
 gradient magnitude :
4.44344738312e+11
 gradient magnitude :
4.33802083366e+11
 gradient magnitude :
4.23509566576e+11
 gradient magnitude :
4.1346125309e+11
 gradient magnitude :
4.03651348867e+11
 gradient magnitude :
3.9407419734e+11
 gra

In [22]:
final_weights

array([-9.99999688e+04,  2.45072603e+02,  6.52795277e+01])

In [24]:
(test_simple_feature_matrix, test_output) =numpy_data(test_data, model_features, my_output)
test_prediction=np.dot(test_simple_feature_matrix,final_weights)
test_prediction

array([366651.41203656, 762662.39786164, 386312.09499712, ...,
       682087.39928241, 585579.27865729, 216559.20396617])

In [25]:
test_data['price']

dtype: float
Rows: 4229
[310000.0, 650000.0, 233000.0, 580500.0, 535000.0, 605000.0, 775000.0, 292500.0, 289000.0, 571000.0, 349000.0, 360000.0, 243500.0, 247500.0, 470000.0, 480000.0, 770000.0, 519950.0, 527700.0, 420000.0, 890000.0, 282950.0, 255000.0, 420000.0, 807100.0, 284000.0, 917500.0, 425000.0, 260000.0, 297000.0, 274250.0, 840000.0, 677900.0, 280000.0, 279950.0, 479950.0, 264950.0, 1025000.0, 2400000.0, 260000.0, 525000.0, 369900.0, 210000.0, 304900.0, 170000.0, 2050000.0, 780000.0, 330000.0, 360000.0, 550000.0, 208633.0, 315000.0, 1384000.0, 1400000.0, 548000.0, 520000.0, 230000.0, 232000.0, 740000.0, 640000.0, 940000.0, 559900.0, 265000.0, 425000.0, 552250.0, 206600.0, 299000.0, 855000.0, 437500.0, 420000.0, 795000.0, 810000.0, 338000.0, 315000.0, 450000.0, 799000.0, 403950.0, 490000.0, 330000.0, 927000.0, 530000.0, 352000.0, 322500.0, 650000.0, 339000.0, 570000.0, 423000.0, 482000.0, 1300000.0, 988000.0, 1000000.0, 350000.0, 205000.0, 333500.0, 255000.0, 348000.0, 325000.0